name: Swift

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Setup Xcode Version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '13.2'

# Package builds
    - name: Build Package
      run: swift build -v
    - name: Run tests
      run: swift test -v
<<<<<<< HEAD
=======
#     - name: Test Wallet
#       working-directory: ./Example
#       run: bundle exec fastlane test_wallet
#     - name: Test Dapp
#       working-directory: ./Example
#       run: bundle exec fastlane test_dapp
      
>>>>>>> develop

# Example app builds
    - name: Build Example Wallet
      run: xcodebuild -project Example/ExampleApp.xcodeproj -scheme Wallet -sdk iphonesimulator
    - name: Build Example Dapp
      run: xcodebuild -project Example/ExampleApp.xcodeproj -scheme DApp -sdk iphonesimulator